// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xt2XiAHya6ZJ8ACtD5U9cE4Iy7xLmMo',
    appId: '1:684943245112:web:4779dc35851e8c0fd24bcd',
    messagingSenderId: '684943245112',
    projectId: 'minetech-backend',
    authDomain: 'minetech-backend.firebaseapp.com',
    storageBucket: 'minetech-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFIYwY9SsplgFTIamytWnEkw75d8BWy68',
    appId: '1:684943245112:android:c43be0d36bf2541bd24bcd',
    messagingSenderId: '684943245112',
    projectId: 'minetech-backend',
    storageBucket: 'minetech-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-2ie20Natd54kXmKR1owHydi5k9Wb9k',
    appId: '1:684943245112:ios:322b8619f3a59411d24bcd',
    messagingSenderId: '684943245112',
    projectId: 'minetech-backend',
    storageBucket: 'minetech-backend.firebasestorage.app',
    iosBundleId: 'com.example.minetechProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-2ie20Natd54kXmKR1owHydi5k9Wb9k',
    appId: '1:684943245112:ios:322b8619f3a59411d24bcd',
    messagingSenderId: '684943245112',
    projectId: 'minetech-backend',
    storageBucket: 'minetech-backend.firebasestorage.app',
    iosBundleId: 'com.example.minetechProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2xt2XiAHya6ZJ8ACtD5U9cE4Iy7xLmMo',
    appId: '1:684943245112:web:41e355aa5a7a6cadd24bcd',
    messagingSenderId: '684943245112',
    projectId: 'minetech-backend',
    authDomain: 'minetech-backend.firebaseapp.com',
    storageBucket: 'minetech-backend.firebasestorage.app',
  );
}
